const extractUserData = (values) => {
	const {
		user_name,
		password,
		first_name,
		middle_name,
		last_name,
		alias_first_name,
		alias_middle_name,
		alias_last_name,
		start_date,
		senority_debit,
		birthday,
		direct_dial,
		work_extension,
		work_cell,
		work_email,
		manager,
		company,
		user_rights,
		position,
		department,
		created_by,
		created_on,
		updated_by,
		updated_on,
		deleted,
		deleted_by,
		deleted_on,
		home_address,
		home_address2,
		home_city,
		home_province,
		home_postal_code,
		home_country,
		personal_cell,
		home_phone,
		personal_email,
		image,
		first_aider,
		ice1name,
		ice1phone1,
		ice1phone2,
		ice2name,
		ice2phone1,
		ice2phone2,
		po_access,
		quote_access,
		project_access,
		parking_pass,
		v1_license_plate,
		v1_man,
		v1_model,
		v1_colour,
		v2_license_plate,
		v2_man,
		v2_model,
		v2_colour,
		external_access,
		external_password,
		forklift,
		skidsteer,
		crane,
		loader,
		engineer,
		healthcare_number,
		ice1relationship,
		ice2relationship,
		allergies_dietary_concerns,
		medical_concerns,
		shirt_size,
		favorite_activities,
		favorite_color,
		favorite_gift_cards,
		favorite_treat,
		boot_tool_allowance,
		activated_on,
		activated_by,
	} = values;

	const userData = {
		user_name: user_name?.trim() || '',
		password: password?.trim() || '',
		first_name: first_name?.trim() || '',
		middle_name: middle_name?.trim() || '',
		last_name: last_name?.trim() || '',
		alias_first_name: alias_first_name?.trim() || '',
		alias_middle_name: alias_middle_name?.trim() || '',
		alias_last_name: alias_last_name?.trim() || '',
		start_date: start_date || null,
		senority_debit: senority_debit || 0,
		birthday: birthday || null,
		direct_dial: direct_dial?.trim() || '',
		work_extension: work_extension?.trim() || '',
		work_cell: work_cell?.trim() || '',
		work_email: work_email?.trim() || '',
		manager: manager || null,
		company: 1,
		user_rights: user_rights || null,
		position: position || null,
		department: department || null,
		created_by: created_by || null,
		created_on: created_on || null,
		updated_by: updated_by || null,
		updated_on: updated_on || null,
		deleted: deleted || 0,
		deleted_by: deleted_by || null,
		deleted_on: deleted_on || null,
		home_address: home_address?.trim() || '',
		home_address2: home_address2?.trim() || '',
		home_city: home_city?.trim() || '',
		home_province: home_province?.trim() || '',
		home_postal_code: home_postal_code?.trim() || '',
		home_country: home_country?.trim() || '',
		personal_cell: personal_cell?.trim() || '',
		home_phone: home_phone?.trim() || '',
		personal_email: personal_email?.trim() || '',
		image: image || '',
		first_aider: first_aider || 1,
		ice1name: ice1name?.trim() || '',
		ice1phone1: ice1phone1?.trim() || '',
		ice1phone2: ice1phone2?.trim() || '',
		ice2name: ice2name?.trim() || '',
		ice2phone1: ice2phone1?.trim() || '',
		ice2phone2: ice2phone2?.trim() || '',
		po_access: po_access || 0,
		quote_access: quote_access || 0,
		project_access: project_access || 0,
		parking_pass: parking_pass || '',
		v1_license_plate: v1_license_plate?.trim() || '',
		v1_man: v1_man?.trim() || '',
		v1_model: v1_model?.trim() || '',
		v1_colour: v1_colour?.trim() || '',
		v2_license_plate: v2_license_plate?.trim() || '',
		v2_man: v2_man?.trim() || '',
		v2_model: v2_model?.trim() || '',
		v2_colour: v2_colour?.trim() || '',
		external_access: external_access || null,
		external_password: external_password || '',
		forklift: forklift || null,
		skidsteer: skidsteer || null,
		crane: crane || null,
		loader: loader || null,
		engineer: engineer || false,
		healthcare_number: healthcare_number?.trim() || '',
		ice1relationship: ice1relationship?.trim() || '',
		ice2relationship: ice2relationship?.trim() || '',
		allergies_dietary_concerns: allergies_dietary_concerns?.trim() || '',
		medical_concerns: medical_concerns?.trim() || '',
		shirt_size: shirt_size?.trim() || '',
		favorite_activities: favorite_activities?.trim() || '',
		favorite_color: favorite_color?.trim() || '',
		favorite_gift_cards: favorite_gift_cards?.trim() || '',
		favorite_treat: favorite_treat?.trim() || '',
		boot_tool_allowance: boot_tool_allowance || '',
		activated_on: activated_on || null,
		activated_by: activated_by || null,
	};
	return userData;
};

module.exports = {
	extractUserData,
};
